.pc
.TH Prompt.rakumod 1 2024-01-24
.SS Table of Contents
.IP \(bu 2m
NAME [#name]
.IP \(bu 2m
AUTHOR [#author]
.IP \(bu 2m
VERSION [#version]
.IP \(bu 2m
TITLE [#title]
.IP \(bu 2m
SUBTITLE [#subtitle]
.IP \(bu 2m
COPYRIGHT [#copyright]
.IP \(bu 2m
Introduction [#introduction]
.IP \(bu 2m
class Gzz_readline [#class-gzz_readline] or on raku\&.land class Gzz_readline [#class-gzz-readline]
.SH "NAME"
Gzz::Prompt 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
0\&.1\&.1
.SH "TITLE"
Gzz::Prompt
.SH "SUBTITLE"
A Raku module to do basic prompting with editing and like readline but with the ability to prefill the value\&.
.SH "COPYRIGHT"
LGPL V3\&.0+ LICENSE [https://github.com/grizzlysmit/Syntax-Highlighters/blob/main/LICENSE]

Top of Document [#table-of-contents]
.SH Introduction

A Raku module to do basic prompting with editing and like readline but with the ability to prefill the value\&.

\fBNB: I use the NativeCall module to get at a C library gzz_readline\&.so which is a fork of the readline library, I had to fork it as it doesn't normally allow you to prefill the value\fR See gzzReadline [https://github.com/grizzlysmit/gzzReadline]\&.

NOTE: you must install gzzReadline to use this [https://github.com/grizzlysmit/gzzReadline]
.SS class Gzz_readline

.RS 4m
.EX
class Gzz_readline is export 


.EE
.RE
.P
Top of Document [#table-of-contents]
